import type { FilterPanelState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: FilterPanelState, fileName = "filter-panel"): ExportPayload {
  return {
    fileName: `${fileName || "filter-panel"}.jsx`,
    mimeType: "text/plain;charset=utf-8",
    content: buildReactCode(state),
  };
}

export function buildReactCode(state: FilterPanelState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
  "",
  "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + \"\ , sans-serif' : \"inherit\"; }",
  "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "const CATEGORY_OPTIONS = [\"Analytics\", \"Billing\", \"Customers\", \"Inventory\", \"Regions\", \"Teams\", \"Risk\", \"Lifecycle\"];",
    "const TOGGLE_OPTIONS = [\"In stock\", \"On sale\", \"Verified\", \"Recently updated\", \"High priority\", \"Has notes\", \"Requires review\", \"Archived\"];",
    "",
    "function clamp(value, min, max) {",
    "  return Math.max(min, Math.min(max, value));",
    "}",
    "",
    "export default function FilterPanelComponent() {",
    "  const groupCount = clamp(Number(state.groupCount) || 3, 1, 8);",
    "  const filterCount = clamp(Number(state.filterCount) || 6, 1, 16);",
    "  const visibleCategories = CATEGORY_OPTIONS.slice(0, groupCount);",
    "  const visibleToggles = TOGGLE_OPTIONS.slice(0, Math.max(2, Math.min(filterCount - 3, TOGGLE_OPTIONS.length)));",
    "  const appliedCount = clamp(Number(state.appliedCount) || 0, 0, visibleCategories.length);",
    "  const describedBy = `${state.id}-description ${state.id}-helper`;",
    "  const [chipHover, setChipHover] = React.useState(-1);",
    "  const [removeHover, setRemoveHover] = React.useState(-1);",
    "  const [applyHover, setApplyHover] = React.useState(false);",
    "  const [resetHover, setResetHover] = React.useState(false);",
    "  const shellStyle = {",
    "    width: state.width,",
    "    minHeight: state.height,",
    "    display: \"grid\",",
    "    gap: state.gap,",
    "    padding: state.padding,",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px ${state.borderStyle} ${state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border}`,",
    "    boxShadow: `0 ${Math.round(state.shadow / 3)}px ${state.shadow}px rgba(15, 23, 42, 0.26)`,",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: resolveFont(state),",
    "    cursor: state.disabled ? state.disabledCursor : undefined,",
    "    opacity: state.disabled ? 0.58 : 1,",
    "  };",
    "  const fieldsetStyle = { display: \"grid\", gap: 10, margin: 0, padding: 14, border: `1px solid ${state.groupDividerColor}`, borderRadius: Math.max(12, state.radius - 8), transition: state.transitionDuration > 0 ? \"border-color 0.2s ease, opacity 0.2s ease\" : \"none\" };",
    "  const legendStyle = { color: state.groupHeaderColor, fontSize: state.groupHeaderSize, fontWeight: 600 };",
    "  const labelStyle = { display: \"grid\", gap: 6, color: state.foreground, fontSize: state.bodySize };",
    "  const controlStyle = { width: \"100%\", border: `1px solid ${state.border}`, borderRadius: 12, padding: \"10px 12px\", background: \"transparent\", color: state.foreground };",
    "",
    "  return (",
    "    <form id={state.id} role={state.role} aria-label={state.ariaLabel} aria-describedby={describedBy} style={shellStyle}>",
    "      <header style={{ display: \"grid\", gap: 6, background: state.panelHeaderBg, borderBottom: `1px solid ${state.panelHeaderBorder}`, paddingBottom: 12 }}>",
    "        <div style={{ display: \"flex\", alignItems: \"center\", justifyContent: \"space-between\", gap: 12 }}>",
    "          <h2 style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "          {appliedCount > 0 ? <span style={{ display: \"grid\", placeItems: \"center\", minWidth: 22, height: 22, borderRadius: 999, padding: \"0 8px\", fontSize: 12, fontWeight: 700, background: state.badgeCountBg, color: state.badgeCountText }}>{appliedCount}</span> : null}",
    "        </div>",
    "        <p id={`${state.id}-description`} style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "      </header>",
    "",
    "      <fieldset style={fieldsetStyle}>",
    "        <legend style={legendStyle}>{state.label} search{state.collapseEnabled ? \" ▾\" : \"\"}</legend>",
    "        <label htmlFor={`${state.id}-query`} style={labelStyle}>",
    "          Search keywords",
    "          <input id={`${state.id}-query`} name=\"query\" type=\"search\" placeholder=\"Search by name, owner, or tag\" aria-describedby={`${state.id}-query-help`} disabled={state.disabled} style={controlStyle} />",
    "        </label>",
    "        <p id={`${state.id}-query-help`} style={{ margin: 0, color: state.muted, fontSize: 12 }}>Use text search before narrowing categories or ranges.</p>",
    "      </fieldset>",
    "",
    "      <fieldset style={fieldsetStyle}>",
    "        <legend style={legendStyle}>Categories{state.collapseEnabled ? \" ▾\" : \"\"}</legend>",
    "        <label htmlFor={`${state.id}-category`} style={labelStyle}>",
    "          Category",
    "          <select id={`${state.id}-category`} name=\"category\" defaultValue={visibleCategories[0]} disabled={state.disabled} style={controlStyle}>",
    "            {visibleCategories.map((category) => <option key={category} value={category}>{category}</option>)}",
    "          </select>",
    "        </label>",
    "        {state.showChips && (",
    "          <div aria-label=\"Applied filters\" style={{ display: \"flex\", flexWrap: \"wrap\", gap: 8 }}>",
    "            {visibleCategories.slice(0, appliedCount).map((category, index) => (",
    "              <span key={category} onMouseEnter={() => setChipHover(index)} onMouseLeave={() => setChipHover(-1)} style={{ display: \"inline-flex\", alignItems: \"center\", gap: 6, border: `1px solid ${state.chipBorder}`, borderRadius: state.chipRadius, padding: \"4px 10px\", color: state.chipText, background: chipHover === index ? state.chipHoverBg : state.chipBg, transition: state.transitionDuration > 0 ? \"background 0.15s ease, border-color 0.15s ease\" : \"none\" }}>",
    "                {category}",
    "                <span role=\"button\" aria-label={\"Remove \" + category} onMouseEnter={() => setRemoveHover(index)} onMouseLeave={() => setRemoveHover(-1)} style={{ display: \"grid\", placeItems: \"center\", width: 16, height: 16, borderRadius: 999, color: state.chipRemoveColor, background: removeHover === index ? state.chipRemoveHoverBg : \"transparent\" }}>",
    "                  <svg aria-hidden=\"true\" width=\"9\" height=\"9\" viewBox=\"0 0 9 9\" fill=\"none\"><path d=\"M1.5 1.5l6 6M7.5 1.5l-6 6\" stroke=\"currentColor\" strokeWidth=\"1.4\" strokeLinecap=\"round\" /></svg>",
    "                </span>",
    "              </span>",
    "            ))}",
    "          </div>",
    "        )}",
    "      </fieldset>",
    "",
    "      <fieldset style={fieldsetStyle}>",
    "        <legend style={legendStyle}>Range and toggles{state.collapseEnabled ? \" ▾\" : \"\"}</legend>",
    "        <label htmlFor={`${state.id}-range`} style={labelStyle}>",
    "          Minimum match score",
    "          <input id={`${state.id}-range`} name=\"score\" type=\"range\" min=\"0\" max=\"100\" defaultValue=\"62\" aria-describedby={`${state.id}-range-help`} disabled={state.disabled} />",
    "        </label>",
    "        <p id={`${state.id}-range-help`} style={{ margin: 0, color: state.muted, fontSize: 12 }}>Higher values reduce results to stronger matches.</p>",
    "        <div style={{ display: \"grid\", gap: 8 }}>",
    "          {visibleToggles.map((option, index) => (",
    "            <label key={option} style={{ display: \"flex\", alignItems: \"center\", gap: 8 }}>",
    "              <input name=\"flags\" type=\"checkbox\" value={option} defaultChecked={index < appliedCount} disabled={state.disabled} />",
    "              <span>{option}</span>",
    "            </label>",
    "          ))}",
    "        </div>",
    "      </fieldset>",
    "",
    "      <label htmlFor={`${state.id}-sort`} style={labelStyle}>",
    "        Sort results",
    "        <select id={`${state.id}-sort`} name=\"sort\" defaultValue=\"relevance\" disabled={state.disabled} style={controlStyle}>",
    "          <option value=\"relevance\">Relevance</option>",
    "          <option value=\"newest\">Newest first</option>",
    "          <option value=\"priority\">Priority</option>",
    "        </select>",
    "      </label>",
    "",
    "      {state.showApplyReset && (",
    "        <div style={{ display: \"flex\", flexWrap: \"wrap\", gap: 10 }}>",
    "          <button type=\"submit\" disabled={state.disabled} onMouseEnter={() => setApplyHover(true)} onMouseLeave={() => setApplyHover(false)} style={{ border: 0, borderRadius: 12, padding: \"10px 14px\", background: applyHover ? state.applyHoverBg : state.applyBg, color: state.applyText, fontWeight: 700, transition: state.transitionDuration > 0 ? \"background 0.15s ease, opacity 0.15s ease\" : \"none\" }}>Apply filters</button>",
    "          <button type=\"reset\" disabled={state.disabled} onMouseEnter={() => setResetHover(true)} onMouseLeave={() => setResetHover(false)} style={{ border: `1px solid ${state.resetBorder}`, borderRadius: 12, padding: \"10px 14px\", background: resetHover ? state.resetHoverBg : state.resetBg, color: state.resetText, transition: state.transitionDuration > 0 ? \"border-color 0.15s ease, color 0.15s ease\" : \"none\" }}>Reset filters</button>",
    "        </div>",
    "      )}",
    "",
    "      <p id={`${state.id}-helper`} role=\"status\" aria-live=\"polite\" style={{ margin: 0, color: state.muted, fontSize: 12 }}>{state.helper}</p>",
    "    </form>",
    "  );",
    "}",
    "",
  ].join("\n");
}
